### ISSUE TITLE
The app won't start

### ISSUE THREAD

**Issue by iKirby** [zllovesuki/ROGManager#28]
Hi,

I would like to try this app so I downloaded it from GitHub release, but it didn't work.

When I started the app, it adjusted fan curve to 'Fanless' (guessing from the noise). Then I pressed function keys but they did nothing. From Windows Task Manager I couldn't find its process, and there is no log file created.

I have disabled all ASUS services. The registry key created by ROGManager, `HKLM\SOFTWARE\ROGManeger` (this is a typo I think?), is empty.

Any help would be appreciated.

System info
Model: G14 R7-4800HS + RTX2060MaxQ, without Anime Matrix
OS: Windows 10 Pro version 2004 build 19041.450
No Armoury Crate installed

**Comment by zllovesuki** [comment]
Hello, please download the debug build of the binary [here](https://rachel.objectstore.co/dist/ROGManager-Debug.exe).

Once you have it downloaded, open a Powershell/Windows Terminal with Administrator privilege then run the binary, and attach the full logs here.

**Comment by iKirby** [comment]
Thanks for your reply. Here is the console output.

```
2020/08/21 12:30:31 Loading configuration from Registry
2020/08/21 12:30:31 Loading "KeyboardControl" from the Registry
2020/08/21 12:30:31 Loading "BatteryChargeLimit" from the Registry
2020/08/21 12:30:31 Loading "ThermalProfile" from the Registry
2020/08/21 12:30:31 Loading "PowerCfg" from the Registry
2020/08/21 12:30:31 Applying "BatteryChargeLimit" config
2020/08/21 12:30:31 device \\.\ATKACPI input buffer: [68 69 86 83 8 0 0 0 87 0 18 0 80 0 0 0]
2020/08/21 12:30:31 device \\.\ATKACPI write result length: 1024
2020/08/21 12:30:31 Applying "ThermalProfile" config
2020/08/21 12:30:31 device \\.\ATKACPI input buffer: [68 69 86 83 8 0 0 0 117 0 18 0 2 0 0 0]
2020/08/21 12:30:31 device \\.\ATKACPI write result length: 1024
2020/08/21 12:30:31 thermal throttle plan set: 0x2
2020/08/21 12:30:31 device \\.\ATKACPI input buffer: [68 69 86 83 20 0 0 0 36 0 17 0 39 49 59 69 79 89 99 109 0 0 0 0 31 49 56 56]
2020/08/21 12:30:31 device \\.\ATKACPI write result length: 1024
2020/08/21 12:30:31 device 0x24 curve set to [39 49 59 69 79 89 99 109 0 0 0 0 31 49 56 56]
2020/08/21 12:30:31 device \\.\ATKACPI input buffer: [68 69 86 83 20 0 0 0 37 0 17 0 39 49 59 69 79 89 99 109 0 0 0 0 34 51 61 61]
2020/08/21 12:30:31 device \\.\ATKACPI write result length: 1024
2020/08/21 12:30:31 device 0x25 curve set to [39 49 59 69 79 89 99 109 0 0 0 0 34 51 61 61]
2020/08/21 12:30:31 Error applying "ThermalProfile": Cannot find target power plan
2020/08/21 12:30:31 Cannot find target power plan
```
It's because that my fresh installed Windows 10 has only one power plan "Balanced". After creating the other two power plans, the app works well.

Changing power plans can be annoying as they have independent brightness values, and I would have to adjust brightness manually every time when I change power plan (because environment lighting changes). So personally I keep using Balanced plan. I think it would be great to have an option to toggle whether to change Windows power plan when changing fan curve.

**Comment by zllovesuki** [comment]
I will keep that in mind when I implement customizable config. Thank you

**Comment by iKirby** [comment]
Thanks for the follow-up. I will close this issue as my problem has been solved.

Perhaps you should add this info to readme, because in fresh Windows 10 installation the one and only power plan available is "Balanced". Users need to create other plans manually.

By the way, in Windows 10 we have this "Power mode" slider. I think this is why Microsoft removed the other two plans.

![snipaste20200821_144119](https://user-images.githubusercontent.com/6316115/90861435-4e968480-e3be-11ea-9b23-0d8e9f868060.png)
